#!/usr/bin/env python3
"""Public shell drift guard for GoHireHumans static pages.

Two layers:

1. The canonical partials (frontend/partials/public-nav.html and
   public-footer.html) keep their marketplace-first tokens.
2. Every public HTML page under frontend/ (recursive, skipping partials/,
   node_modules/, test-results/ and playwright-report/) carries the shared
   baseline: exactly one canonical nav wrapper, exactly one canonical footer,
   a skip link, a main landmark, the analytics bootstrap, exactly one
   theme-color meta, and no legacy shells, empty hrefs or builder attribution.
   index.html renders its nav and footer from JavaScript templates, so only
   the two exactly-once shell checks are skipped for it.

Prints a per-file problem list plus a count per problem type and exits 1 on
any drift. The contract is documented in docs/design-system/public-shell.md.
"""
from collections import Counter
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / 'frontend'
SKIP_DIRS = {'node_modules', 'test-results', 'playwright-report', 'partials', '.git', 'dist', 'build'}

REQUIRED_FILES = [
    'frontend/partials/public-nav.html',
    'frontend/partials/public-footer.html',
    'docs/design-system/public-shell.md',
    'docs/design-system/design-system.md',
    'scripts/sync_public_shell.py',
]
NAV_TOKENS = ['Marketplace', 'Find Work', 'For Agents', 'Pricing', 'Trust', 'Post a task', 'lp-nav']
FOOTER_TOKENS = [
    'lp-footer', 'Find Work', 'Starter Offers',
    'gohirehumans.operations@agentmail.to', 'Direct-payment instructions are not allowed',
]

NAV_WRAP = '<div class="lp-nav-wrap">'
FOOTER = '<footer class="lp-footer"'
SKIP_LINK = '<a class="skip-link" href="#main-content">'
MAIN_LANDMARK = '<main id="main-content"'
ANALYTICS_BOOTSTRAP = 'src="/analytics-bootstrap.js"'
THEME_COLOR = '<meta name="theme-color"'

# substring -> problem label
FORBIDDEN = {
    'Perplexity': 'builder attribution: Perplexity',
    'perplexity.ai': 'builder attribution: perplexity.ai',
    'Created with': 'builder attribution: "Created with"',
    'Generated by': 'builder attribution: "Generated by"',
    '<footer class="site-footer"': 'legacy footer: footer.site-footer',
    '<footer class="footer"': 'legacy footer: footer.footer',
    '<footer class="ftr"': 'legacy footer: footer.ftr',
    '<div class="footer">': 'legacy footer: div.footer',
    '<header class="header">': 'legacy header: header.header',
    'href=""': 'empty href=""',
}

# High-visibility conversion/trust pages keep the marketplace-first labels and
# owned CTAs in addition to the baseline above.
CRITICAL_PAGES = [
    'frontend/index.html',
    'frontend/starter-offers.html',
    'frontend/pricing.html',
    'frontend/trust-safety.html',
    'frontend/proof-packs.html',
    'frontend/stats.html',
    'frontend/use-cases/index.html',
]


def public_pages():
    pages = []
    for path in sorted(FRONTEND.rglob('*.html')):
        rel = path.relative_to(FRONTEND)
        if SKIP_DIRS.intersection(rel.parts[:-1]):
            continue
        pages.append(path)
    return pages


def page_problems(path, text):
    rel = str(path.relative_to(ROOT))
    is_spa = path == FRONTEND / 'index.html'
    issues = []
    if not is_spa:
        nav_count = text.count(NAV_WRAP)
        if nav_count != 1:
            issues.append(f'canonical nav wrapper count {nav_count} (expected 1)')
        footer_count = text.count(FOOTER)
        if footer_count != 1:
            issues.append(f'canonical footer count {footer_count} (expected 1)')
    for needle, label in FORBIDDEN.items():
        if needle in text:
            issues.append(label)
    if SKIP_LINK not in text:
        issues.append('missing skip link')
    if MAIN_LANDMARK not in text:
        issues.append('missing main landmark')
    if ANALYTICS_BOOTSTRAP not in text:
        issues.append('missing analytics bootstrap')
    theme_count = text.count(THEME_COLOR)
    if theme_count != 1:
        issues.append(f'theme-color meta count {theme_count} (expected 1)')
    if rel in CRITICAL_PAGES:
        if 'Find Work' not in text or 'Post a task' not in text:
            issues.append('missing marketplace-first shell labels')
        if '<li><a href="/#/jobs">Open Jobs</a></li>' in text:
            issues.append('ambiguous worker jobs footer label')
        if rel == 'frontend/stats.html' and 'Get started' in text:
            issues.append('generic stats CTA')
    return issues


def problem_type(issue):
    # Collapse the numeric detail so counts group by problem kind.
    return issue.split(' count ')[0] if ' count ' in issue else issue


def main():
    missing = [rel for rel in REQUIRED_FILES if not (ROOT / rel).exists()]
    if missing:
        print('Missing public shell assets:', missing)
        return 1

    nav = (ROOT / 'frontend/partials/public-nav.html').read_text(encoding='utf-8', errors='ignore')
    footer = (ROOT / 'frontend/partials/public-footer.html').read_text(encoding='utf-8', errors='ignore')
    for token in NAV_TOKENS:
        if token not in nav:
            print('Missing nav token', token)
            return 1
    for token in FOOTER_TOKENS:
        if token not in footer:
            print('Missing footer token', token)
            return 1

    pages = public_pages()
    missing_critical = [rel for rel in CRITICAL_PAGES if not (ROOT / rel).exists()]
    if missing_critical:
        print('Missing critical public pages:', missing_critical)
        return 1

    problems = {}
    for path in pages:
        text = path.read_text(encoding='utf-8', errors='ignore')
        issues = page_problems(path, text)
        if issues:
            problems[str(path.relative_to(ROOT))] = issues

    if problems:
        print(f'Public shell drift detected in {len(problems)} of {len(pages)} pages:')
        for rel, issues in problems.items():
            print(f'- {rel}: {"; ".join(issues)}')
        counts = Counter(problem_type(issue) for issues in problems.values() for issue in issues)
        print('\nProblem counts:')
        for label, count in sorted(counts.items(), key=lambda item: (-item[1], item[0])):
            print(f'  {count:4d}  {label}')
        return 1

    print(f'Public shell assets OK ({len(pages)} pages checked)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
